Allow enums with only one item
grafana/cuetsy pull request #77
Opened 2023-02-08 16:24 UTC by spinillos

Fixes: https://github.com/grafana/schematization-and-as-code-project/issues/74

We were forcing to have at least two elements.

2023-02-08 17:37 UTC, Clarity-89 approved these changes

2023-02-10 11:24 UTC, sdboyer requested changes
just some small things.

it might be nice to have some more tests that explore expected failure cases here, especially with removing the `cue.OrOp` check - but only if it's easy, as it's hard to picture anything but intentional misuse there.

2023-02-10 11:24 UTC, sdboyer commented on generator.go
>  		g.addErr(valError(v, "typescript enums may only be generated from a disjunction of concrete int with memberNames attribute or strings"))
```suggestion
		g.addErr(valError(v, "typescript enums may only be generated from concrete strings, or ints with memberNames attribute"))
```

2023-02-10 11:24 UTC, sdboyer commented on generator.go
>  	allowed := cue.StringKind | cue.NumberKind | cue.NumberKind
this is weird. while we're in here, could we fix this? seems like this should be:
```suggestion
	allowed := cue.StringKind | cue.IntKind
```
though i am cognizant that the kinds of numeric values are less than dependable, see e.g. grafana/thema#111

2023-02-10 15:18 UTC, spinillos commented
If you use something different than `cue.OrOp`, it fails with different error.

2023-02-22 04:36 UTC, sdboyer approved these changes

2023-02-22 04:36 UTC, merged